### PR TITLE
ENH Add new maintainers

### PR DESCRIPTION
**Pull request by stephen-hoover**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adding new maintainers.

### CODE REVIEW

**Comment by stephen-hoover** [comment]
@conda-forge-admin, please rerender

**Review by beckermr — APPROVED** [review]
LGTM!

**Comment by stephen-hoover** [comment]
Thank you!

**Comment by stephen-hoover** [comment]
@conda-forge-admin, please update team

**Pull request merged**
